# Dataset
data_name = 'ml-1m'
neg_num = 4
test_neg_num = 100
num_workers = 1

# Model
mlp_dims = [512, 256, 128, 64]
user_mlp_dims = [512, 64]
item_mlp_dims = [1024, 64]

# Train
batch_size = 512
epoch_num = 100
learning_rate = 1e-3
lambda = 1e-3

# Test
topk = 10

